In [27]:
#INSTALAR LIBRERIAS
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn
!pip install openpyxl
!pip install sympy

In [28]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sympy import primerange

In [29]:
#Convertimos el dataset en dataframe
df= pd.read_csv("Amsterdam.csv")
df

,id,name,host_id,host_profile_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,28871,Comfortable double room,1.242450e+05,1.462510e+18,Edwin,NaN,Centrum-West,52.367750,4.890920,Private room,94.0,1.0,799,2026-06-01,4.15,2.0,11,88,0363 607B EA74 0BD8 2F6F
1,29051,Comfortable single / double room,1.242450e+05,1.462510e+18,Edwin,NaN,Centrum-Oost,52.365840,4.891110,Private room,NaN,1.0,906,2026-06-01,4.88,2.0,2,82,0363 607B EA74 0BD8 2F6F
2,44129,Luxury design with canal view,1.877280e+05,1.462512e+18,Tanya,NaN,Centrum-West,52.382110,4.886300,Entire home/apt,314.0,3.0,186,2026-04-30,0.96,4.0,3,5,03635399E87602900F47
3,44391,Quiet 2-bedroom Amsterdam city centre apartment,1.947790e+05,1.462512e+18,Jan,NaN,Centrum-Oost,52.371680,4.914710,Entire home/apt,NaN,3.0,42,2022-08-20,0.22,1.0,0,0,0363 E76E F06A C1DD 172C
4,48373,Cozy family home in Amsterdam South,2.204340e+05,1.462513e+18,Vesna & Misha,NaN,Buitenveldert - Zuidas,52.327808,4.876800,Entire home/apt,NaN,3.0,5,2024-04-28,0.14,1.0,0,0,0363 4A2B A6AD 0196 F684
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10460,1708031597364214682,Lovely room with balcony in the heart of Amste...,1.705253e+18,1.705254e+18,Steven,NaN,De Pijp - Rivierenbuurt,52.350590,4.900670,Private room,126.0,2.0,0,NaN,NaN,7.0,34,0,0363 8C4D 1A2F 4D51 9B6C
10461,1708094794334709654,Keizers Canal Home,4.810698e+08,1.470166e+18,Cornelia,NaN,Centrum-West,52.371481,4.883742,Entire home/apt,588.0,1.0,0,NaN,NaN,2.0,43,0,0363 31C4 7BD8 1F63 4A61
10462,1708105472694968020,Two bedroom apt in the best location of Amsterdam,1.705253e+18,1.705254e+18,Steven,NaN,De Pijp - Rivierenbuurt,52.353741,4.903011,Entire home/apt,259.0,3.0,0,NaN,NaN,7.0,19,0,0363 8C4D 1A2F 4D51 9B6C
10463,1708115205290482378,Single Bedroom apt in the heart of Amsterdam,1.705253e+18,1.705254e+18,Steven,NaN,De Pijp - Rivierenbuurt,52.354500,4.903400,Entire home/apt,162.0,1.0,0,NaN,NaN,7.0,35,0,036302DC0A50A5E48A8A


In [30]:
#Verificamos información del DataFrame
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10465 entries, 0 to 10464
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   id                              10465 non-null  int64  
 1   name                            10465 non-null  str    
 2   host_id                         10369 non-null  float64
 3   host_profile_id                 10232 non-null  float64
 4   host_name                       10227 non-null  str    
 5   neighbourhood_group             0 non-null      float64
 6   neighbourhood                   10465 non-null  str    
 7   latitude                        10465 non-null  float64
 8   longitude                       10465 non-null  float64
 9   room_type                       10465 non-null  str    
 10  price                           6471 non-null   float64
 11  minimum_nights                  10462 non-null  float64
 12  number_of_reviews               10465 non-n

In [31]:
#Convertimos el DataFrame de pandas en un arreglo de numpy
array = df.to_numpy()
array

array([[28871, 'Comfortable double room', 124245.0, ..., 11, 88,
        '0363 607B EA74 0BD8 2F6F'],
       [29051, 'Comfortable single / double room', 124245.0, ..., 2, 82,
        '0363 607B EA74 0BD8 2F6F'],
       [44129, 'Luxury design with canal view', 187728.0, ..., 3, 5,
        '03635399E87602900F47'],
       ...,
       [1708105472694968020,
        'Two bedroom apt in the best location of Amsterdam',
        1.705253369814659e+18, ..., 19, 0, '0363 8C4D 1A2F 4D51 9B6C'],
       [1708115205290482378,
        'Single Bedroom apt in the heart of Amsterdam',
        1.705253369814659e+18, ..., 35, 0, '036302DC0A50A5E48A8A'],
       [1708158632781004601, 'The Grand canal residence', 753265755.0,
        ..., 353, 0, 'AMBN 4821 nk7p 54xd b3f8']],
      shape=(10465, 19), dtype=object)

***Indexación de un array 1D a partir de un array 2D***

In [32]:
# Acceder a la primera fila de un arreglo de numpy
fila0 = array[0]
fila0

array([28871, 'Comfortable double room', 124245.0, 1.462510208428039e+18,
       'Edwin', nan, 'Centrum-West', 52.36775, 4.89092, 'Private room',
       94.0, 1.0, 799, '2026-06-01', 4.15, 2.0, 11, 88,
       '0363 607B EA74 0BD8 2F6F'], dtype=object)

In [33]:
# Acceder a la primera fila de un Dataframe de pandas
fila0 = df.iloc[0]
fila0

id                                                   28871
name                               Comfortable double room
host_id                                           124245.0
host_profile_id                      1462510208428038912.0
host_name                                            Edwin
neighbourhood_group                                    NaN
neighbourhood                                 Centrum-West
latitude                                          52.36775
longitude                                          4.89092
room_type                                     Private room
price                                                 94.0
minimum_nights                                         1.0
number_of_reviews                                      799
last_review                                     2026-06-01
reviews_per_month                                     4.15
calculated_host_listings_count                         2.0
availability_365                                        

In [34]:
# Acceder a la primera fila de un arreglo de numpy
columna0 = array[:, 0]
columna0

array([28871, 29051, 44129, ..., 1708105472694968020, 1708115205290482378,
       1708158632781004601], shape=(10465,), dtype=object)

***Indexación de múltiples arrays 1D a partir de un array 2D***

In [35]:
#Filas consecutivas 3-5 y la columna 4
Filas_3_a_5= array[3:6, 4]       
Filas_3_a_5

array(['Jan', 'Vesna & Misha', 'Joanna & MP'], dtype=object)

In [36]:
#Filas no consecutivas 2, 8, 12 y Todas las columnas
Filas_3_a_5= array[[2, 8, 12], :]       
Filas_3_a_5

array([[44129, 'Luxury design with canal view', 187728.0,
        1.4625121252931446e+18, 'Tanya', nan, 'Centrum-West', 52.38211,
        4.8863, 'Entire home/apt', 314.0, 3.0, 186, '2026-04-30', 0.96,
        4.0, 3, 5, '03635399E87602900F47'],
       [53921, 'Amsterdam Stylish Lakeview Apartment', 252245.0,
        1.4625138100020278e+18, 'Ingrid', nan,
        'IJburg - Zeeburgereiland', 52.35559, 5.0032, 'Entire home/apt',
        nan, 1.0, 12, '2024-05-25', 0.13, 1.0, 0, 0,
        '0363 B43C B1D4 2666 3739'],
       [91535, 'Privat room and shared Houseboat "Ramona" centre',
        494281.0, 1.4625198492251617e+18, 'Michiel', nan,
        'De Pijp - Rivierenbuurt', 52.35774, 4.89647, 'Private room',
        269.0, 1.0, 334, '2026-06-13', 1.84, 1.0, 42, 37,
        '0363 74BA 2074 E0CF 1CB8']], dtype=object)

In [37]:
#Filas combinadas 0, 4-6 y 10 y columna 4
Filas_0_4_5_6_10= array[[0] + list(range(4, 7)) + [10], 4]       
Filas_0_4_5_6_10


array(['Edwin', 'Vesna & Misha', 'Joanna & MP', 'Donald', 'Jessica'],
      dtype=object)

In [38]:
#Filas pares y todas las columnas
Filas_pares = array[::2, :]
Filas_pares

array([[28871, 'Comfortable double room', 124245.0, ..., 11, 88,
        '0363 607B EA74 0BD8 2F6F'],
       [44129, 'Luxury design with canal view', 187728.0, ..., 3, 5,
        '03635399E87602900F47'],
       [48373, 'Cozy family home in Amsterdam South', 220434.0, ..., 0,
        0, '0363 4A2B A6AD 0196 F684'],
       ...,
       [1708031597364214682,
        'Lovely room with balcony in the heart of Amsterdam',
        1.705253369814659e+18, ..., 34, 0, '0363 8C4D 1A2F 4D51 9B6C'],
       [1708105472694968020,
        'Two bedroom apt in the best location of Amsterdam',
        1.705253369814659e+18, ..., 19, 0, '0363 8C4D 1A2F 4D51 9B6C'],
       [1708158632781004601, 'The Grand canal residence', 753265755.0,
        ..., 353, 0, 'AMBN 4821 nk7p 54xd b3f8']],
      shape=(5233, 19), dtype=object)

In [39]:
#Filas impares y todas las columnas
Filas_impares = array[1::2, :]
Filas_impares

array([[29051, 'Comfortable single / double room', 124245.0, ..., 2, 82,
        '0363 607B EA74 0BD8 2F6F'],
       [44391, 'Quiet 2-bedroom Amsterdam city centre apartment',
        194779.0, ..., 0, 0, '0363 E76E F06A C1DD 172C'],
       [49552, 'Multatuli Luxury Guest Suite in top location', 225987.0,
        ..., 278, 57, '0363 576A D827 5085 6B83'],
       ...,
       [1708005776145639009, 'Dam Center Oasis', 481069764.0, ..., 37, 0,
        '0363 834B F21D CE73 4AD8'],
       [1708094794334709654, 'Keizers Canal Home', 481069764.0, ..., 43,
        0, '0363 31C4 7BD8 1F63 4A61'],
       [1708115205290482378,
        'Single Bedroom apt in the heart of Amsterdam',
        1.705253369814659e+18, ..., 35, 0, '036302DC0A50A5E48A8A']],
      shape=(5232, 19), dtype=object)

In [43]:
#Filas primas y todas las columnas
primos = list(primerange(0, 20))
Filas_primas = array[primos, :]
Filas_primas

array([[44129, 'Luxury design with canal view', 187728.0,
        1.4625121252931446e+18, 'Tanya', nan, 'Centrum-West', 52.38211,
        4.8863, 'Entire home/apt', 314.0, 3.0, 186, '2026-04-30', 0.96,
        4.0, 3, 5, '03635399E87602900F47'],
       [44391, 'Quiet 2-bedroom Amsterdam city centre apartment',
        194779.0, 1.4625123369036503e+18, 'Jan', nan, 'Centrum-Oost',
        52.37168, 4.91471, 'Entire home/apt', nan, 3.0, 42, '2022-08-20',
        0.22, 1.0, 0, 0, '0363 E76E F06A C1DD 172C'],
       [49552, 'Multatuli Luxury Guest Suite in top location', 225987.0,
        1.4625131522578511e+18, 'Joanna & MP', nan, 'Centrum-West',
        52.38028, 4.89089, 'Entire home/apt', 440.0, 2.0, 656,
        '2026-06-07', 3.45, 1.0, 278, 57, '0363 576A D827 5085 6B83'],
       [50523, 'B & B de 9 Straatjes (city center)', 231946.0,
        1.4625133203240108e+18, 'Raymond', nan, 'Centrum-West', 52.36959,
        4.88423, 'Entire home/apt', 154.0, 1.0, 631, '2026-05-31', 3.35,
     

In [41]:
#Convertir un arreglo de numpy a CSV
np.savetxt("datos_numpy.csv", array, delimiter=",", fmt="%s", encoding="utf-8")

In [42]:
#Convertir un dataframe de pandas a CSV
df.to_csv("datos_pandas.csv")